kind: Service
apiVersion: v1
metadata:
  name: fancontrol
  namespace: fancontrol
  labels:
    app.kubernetes.io/name: fancontrol
  annotations:
    prometheus.io/path: "/metrics"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: fancontrol
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app.kubernetes.io/name: fancontrol
